version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: optical-shop-mssql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "OpticalShop@123"
      MSSQL_PID: "Developer"
    ports:
      - "1434:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    restart: unless-stopped

volumes:
  mssql_data:
